### ISSUE TITLE
tiny-tunes test: makeURL does not pass what it says it does

### ISSUE THREAD

**Issue by sehnpaa** [1dv021/laborationer#4]
The test cases in makeURL() which uses the parameter path seems to be inconsequent. The description leaves out a leading '/' while the actual test does include it. Please have a look at: https://github.com/1dv021/laborationer/blob/part1-tiny-tunes-15/test/part-1/tiny-tunes/tiny-tunes.test.js#L177-L185

I'm not sure where we should make the change; the description or the passed in argument?

**Comment by thajo** [comment]
Thank you! I think we change the descriptions at this time. I will check fix it as soon as I can.
